const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),JSZip=require('jszip'),{DOMParser,XMLSerializer}=require('@xmldom/xmldom');
const c={JSZip,DOMParser,XMLSerializer,crypto:require('crypto').webcrypto,Uint8Array,atob,btoa};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/engine.js'),'utf8')+';globalThis.e=ThesisEngine;',c);
async function inspect(titles,scheme='humanities',roles={},extra={}){const z=new JSZip(),w='http://schemas.openxmlformats.org/wordprocessingml/2006/main';z.file('word/document.xml','<w:document xmlns:w="'+w+'"><w:body>'+titles.map(([text,role])=>'<w:p>'+(role==='h'?'<w:pPr><w:outlineLvl w:val="0"/></w:pPr>':role==='toc'?'<w:pPr><w:pStyle w:val="TOC1"/></w:pPr>':'')+'<w:r><w:t>'+text+'</w:t></w:r></w:p>').join('')+'<w:sectPr/></w:body></w:document>');return c.e.inspect(await z.generateAsync({type:'uint8array'}),{preset_id:scheme,...extra},roles);}
(async()=>{
let r=await inspect([['1 绪论','h'],['2 数据来源与研究方法','h'],['3 实证分析','h'],['4 结论与展望','h']]);assert(r.structure_hints.items.every(x=>x.status==='recognized'));assert(!r.issues.some(x=>x.kind==='正文结构提示'));
r=await inspect([['1 前言','h'],['2 材料和方法','h'],['3 结果与讨论','h']],'natural');assert(r.structure_hints.items.every(x=>x.status==='recognized'));assert.equal(r.structure_hints.items[2].matches[0].shared_parts.length,2);
r=await inspect([['材料与方法','toc'],['绪论','h'],['正文提到了材料与方法，但这句话不是标题。'],['图1 材料与方法'],['附录'],['结果与分析','h'],['参考文献'],['讨论','h']],'natural');assert.equal(r.structure_hints.items.filter(x=>x.status==='recognized').length,1);assert(r.issues.filter(x=>x.kind==='正文结构提示').every(x=>!x.fix&&x.level==='人工确认'));
r=await inspect([['绪论','h'],['材料与方法','h'],['结果与分析','h'],['讨论','h']],'natural',{'1':'skip'});assert.equal(r.structure_hints.items[1].status,'not_recognized');
r=await inspect([['前言'],['研究方法'],['研究内容'],['研究结论']]);assert(r.structure_hints.items.every(x=>x.status==='recognized'));
r=await inspect([['1 Introduction','h'],['2 Materials and Methods','h'],['3 Results and Discussion','h']],'natural');assert(r.structure_hints.items.every(x=>x.status==='recognized'));
r=await inspect([['绪论','h']],'custom');assert(!r.structure_hints.enabled);r=await inspect([['绪论','h']],'custom',{}, {structure_profile:'natural'});assert(r.structure_hints.enabled&&r.structure_hints.scheme==='natural');r=await inspect([['绪论','h']],'natural',{}, {structure_profile:'off'});assert(!r.structure_hints.enabled);assert(!r.issues.some(x=>x.kind==='正文结构提示'));assert.throws(()=>c.e.validate({structure_profile:'bad'}));
console.log('PASS structure hints: both schemes, aliases, merged sections, English headings, scope exclusion, manual overrides, plain section names, custom selection and off');
})().catch(e=>{console.error(e);process.exit(1)});
